import type { Metadata } from "next";
import { Comfortaa } from "next/font/google";
import "./globals.css";

import Image from "next/image";

import logo from "@/public/logo.svg";
import { CircleUser, LucideArrowRightFromLine } from "lucide-react";
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuLabel,
  DropdownMenuSeparator,
  DropdownMenuTrigger,
} from "@/components/ui/dropdown-menu";
import { Button } from "@/components/ui/button";

const comfortaa = Comfortaa({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Eva",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${comfortaa.className} antialiased`}>
        <header className="mx-auto flex max-w-6xl items-center justify-between px-10 py-5">
          <Image src={logo} alt="Logo" width={120} height={40} unoptimized />
          <div className="flex items-center gap-4">
            <p className="text-sm text-gray-400">Hello, John Doe</p>
            <DropdownMenu>
              <DropdownMenuTrigger className="bg-primary grid h-10 w-10 place-items-center rounded-full">
                <CircleUser className="h-6 w-6 text-white" />
              </DropdownMenuTrigger>
              <DropdownMenuContent align="end">
                <DropdownMenuLabel>My Account</DropdownMenuLabel>
                <DropdownMenuSeparator />
                <DropdownMenuItem>Admin</DropdownMenuItem>
                <DropdownMenuItem>Profile</DropdownMenuItem>
                <DropdownMenuItem>WikiScienta</DropdownMenuItem>
                <DropdownMenuItem>
                  <Button className="w-full text-xs">
                    <LucideArrowRightFromLine className="h-2 w-2 text-white" />
                    Sign out
                  </Button>
                </DropdownMenuItem>
              </DropdownMenuContent>
            </DropdownMenu>
          </div>
        </header>
        {children}
        <footer className="mx-auto flex max-w-6xl items-center justify-center px-10 py-5">
          <p className="text-sm text-gray-400">© 2025 Scienta Lab</p>
        </footer>
      </body>
    </html>
  );
}
