import type { Metadata } from "next";
import { Comfortaa } from "next/font/google";
import Image from "next/image";
import Link from "next/link";

import Nav from "@/components/nav";
import { Toaster } from "@/components/ui/sonner";
import { UserProvider } from "@/components/user-context";

import logo from "@/public/logo.svg";
import "./globals.css";

const comfortaa = Comfortaa({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Eva",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <UserProvider>
        <body className={`${comfortaa.className} antialiased`}>
          <header className="mx-auto flex max-w-6xl items-center justify-between px-10 py-5">
            <Link href="/" className="contents">
              <Image
                src={logo}
                alt="Logo"
                width={120}
                height={40}
                unoptimized
              />
            </Link>
            <Nav />
          </header>
          {children}
          <Toaster
            closeButton
            className="[&_[data-close-button]]:top-3.5! [&_[data-close-button]]:right-0! [&_[data-close-button]]:left-auto!"
          />
        </body>
      </UserProvider>
    </html>
  );
}
